---
name: CI

"on":
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

jobs:
  lint-files:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/transform-ia/claude-image:0.1.2
      options: --user 0
    steps:
      - uses: actions/checkout@v4

      - name: Lint YAML
        run: yamllint .

      - name: Lint Markdown
        run: markdownlint .

  lint-go:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/transform-ia/golang-image:0.0.12
      options: --user 0
    steps:
      - uses: actions/checkout@v4

      - name: Lint Go
        run: golangci-lint run --fix ./...

      - name: Test
        run: go test -v -race ./...
